import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';

import { ThemeProvider } from '@/providers/theme-provider';
import { ConvexClientProvider } from '@/providers/convex-provider';
import StoreProvider from '@/providers/store-provider';

import { Toaster } from 'sonner';
import { CheckCircle, CircleAlert, Info, TriangleAlert } from 'lucide-react';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Synapse',
  description: 'Generated by create next app',
  icons: {
    icon: [
      {
        rel: 'icon',
        media: '(prefers-color-scheme: light)',
        url: '/logo.svg',
        href: '/logo.svg',
      },
      {
        rel: 'icon',
        media: '(prefers-color-scheme: dark)',
        url: '/logo-dark.svg',
        href: '/logo-dark.svg',
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
    >
      <head>
        <link
          rel='icon'
          href='/logo-dark.svg'
          sizes='any'
        />
      </head>
      <body
        className={cn(
          'min-h-screen  bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <ConvexClientProvider>
          <StoreProvider>
            <ThemeProvider
              attribute='class'
              defaultTheme='light'
              disableTransitionOnChange
              storageKey='synapse-theme'
            >
              <Toaster
                position='bottom-center'
                toastOptions={{
                  classNames: {
                    success:
                      'w-auto bg-background text-dark border-1 border-green-500 dark:text-white flex flex-row gap-x-5',
                    error:
                      'w-auto bg-background text-dark border-1 border-red-500 dark:text-white flex flex-row gap-x-5',
                    warning:
                      'w-auto bg-background text-dark border-1 border-yellow-500 dark:text-white flex flex-row gap-x-5',
                    info: 'w-auto bg-background text-dark border-1 border-blue-500 dark:text-white flex flex-row gap-x-5',
                  },
                }}
                icons={{
                  success: (
                    <CheckCircle
                      className='w-7 h-7'
                      color='#22c55e'
                    />
                  ),
                  error: (
                    <CircleAlert
                      className='w-7 h-7'
                      color='#ef4444'
                    />
                  ),
                  warning: (
                    <TriangleAlert
                      className='w-7 h-7'
                      color='#eab308'
                    />
                  ),
                  info: (
                    <Info
                      className='w-7 h-7'
                      color='#3b82f6'
                    />
                  ),
                }}
              />
              {children}
            </ThemeProvider>
          </StoreProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
